### ISSUE TITLE
Programm Start?

### ISSUE THREAD

**Issue by Heisenberg9469** [fxsth/Audiothekar#1]
Guten Tag,
wie starte ich dieses Programm?
Leider habe ich keine erfahrungen mit C+

**Comment by fxsth** [comment]
Hi,
lad dir einfach die ausführbare Datei audiothek-cli.exe herunter. Die findest du unter den Releases https://github.com/fxsth/Audiothekar/releases/latest
Die exe kannst du per Doppelklick starten oder über cmd/Powershell aufrufen.
Möglicherweise wird Windows beim Starten noch einen Warnhinweis anzeigen, dass das Programm aus unbekannter Quelle stammt.

**Comment by Heisenberg9469** [comment]
Auf die idee hätt ich auch mal kommen können... danke dir, auch für das Super Programm!
